## Importing Necessary Modules
import requests # to get image from the web
import shutil # to save it locally

## Set up the image URL and filename
imagesList = ['https://bigd.big.ac.cn/idog/images/breed_image_thumb/Bouvier_Des_Ardennes.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Braque_de_l_Ariege.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Braque_Saint_Germain.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Briquet_Griffon_Vendeen.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Ca_de_Bestiar__Majorca_Shepherd_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Cao_de_Castro_Laboreiro.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Catalonian_Sheepdog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Cesky_Fousek.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Chart_Polski__Polish_Greyhound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Chien_d_Artois.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Chien_Francais_Blanc_et_Noir.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Chien_Francais_Tricolore.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Cimarron_Uruguayo.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Ciobanesc_Romanesc_Carpatin.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Ciobanesc_Romanesc_Mioritic.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Croatian_Sheepdog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Deutsche_Bracke.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Dunker.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Dutch_Smoushond.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/East_Siberian_Laika.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/English_Shepherd.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Epagneul_Pont_Audemer.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Epagneul_Picard.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Finnish_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Francais_Blanc_et_Orange.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Fresian_Water_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/German_Rough_Haired_Pointer.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Grand_Bleu_De_Gascogne.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Grand_Gascon_Saintongeois.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Grand_Griffon_Vendeen.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Grand_anglo_francais_tricol.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Great_Anglo-Francais_White_and_Black_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Great_Anglo-Francais_White_and_Orange_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Griffon_Bleu_de_Gascogne.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Griffon_Fauve_de_Bretagne.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Griffon_Nivernais.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Haldenstover__Halden_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hanoverian_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hellenic_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hungarian_Greyhound__Magyar_Agar.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hygen_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Istrian_Short_Haired_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Italian_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Jack_Russell_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Japanese_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Kangal_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Karst_Shepherd_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Kooikerhondje.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Majorca_Mastiff.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Maremma_Sheepdog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Mi-Ki.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Montenegrin_Mountain_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Mountain_Feist.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Norrbottenspets.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Old_Danish_Pointing_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Olde_English_Bulldogge.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Patterdale_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Perdiguero_de_Burgos.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Petit_Bleu_De_Gascogne.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Petit_Gascon_Saintongeois.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Podenco_Canario.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Poitevin.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Polish_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Posavaz_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Russian_European_Laika.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Saarloosewolfdog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Sarplaninac.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Schiller_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Serbian_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Serbian_Tricolor_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Silken_Windhound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Slovakian_Wire_Haired_Pointing_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Smaland_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Small_Swiss_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/South_Russian_Shepherd_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Spanish_Greyhound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Spanish_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Sporting_Lucas_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Stephens_Cur.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Styrian_Coarse_Haired_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Swedish_Elkhound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Swiss_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Treeing_Cur.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Treeing_Feist.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Tyrolean_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Volpino_Italiano.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Welsh_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/West_Siberian_Laika.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Westphalian_Dachsbracke.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/White_Shepherd.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Alpine_Dachsbracke.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/American_Akita.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Brazilian_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Continental_Toy_Spaniel.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/English_Toy_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Entlebuch_Cattle_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Fila_Brasileiro.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/French_White_And_Orange_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Gascon_Saintongeois.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Griffon_Belge.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Griffon_Bruxellois.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hanoverian_Scent_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hungarian_Hound__Transylvanian_Scent_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hungarian_Short_haired_Pointer__vizsla.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Istrian_Wire_haired_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Italian_Rough_haired_Segugio.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Italian_Short_haired_Segugio.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Landseer.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Long_haired_Pyrenean_Sheepdog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Norwegian_Elkhound_Black.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Peruvian_Hairless_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Petit_Brabancon.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Polish_Hunting_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Posavatz_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Pyrenean_Sheepdog__Smooth_Faced.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Saint_Miguel_Cattle_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Schnauzer.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Southeastern_European_Shepherd.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Thai_Bangkaew_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/White_Swiss_Shepherd_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Yugoslavian_Shepherd_Dog__Sharplanina.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Alaunt.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Alpine_Mastiff.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Alpine_Spaniel.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Blue_Paul_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Braque_du_Puy.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Bullenbeisser.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Chien_gris.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Chinese_Chongqing_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Chinese_Imperial_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Cordoba_Fighting_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Cumberland_Sheepdog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Dogo_Cubano.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/English_Water_Spaniel.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/English_White_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hare_Indian_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Hawaiian_Poi_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Kunming_Wolfdog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Kuri.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Miniature_Shar_Pei.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Molossus.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Moscow_Water_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Norfolk_Spaniel.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/North_Country_Beagle.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Paisley_Terrier.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Rastreador_Brasileiro.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Russian_Tracker.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Seskar_Seal_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Southern_Hound.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/St_John_s_water_dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Tahltan_Bear_Dog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Talbot.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Toy_Bulldog.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Toy_Trawler_Spaniel.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Tweed_Water_Spaniel.jpg'
,'https://bigd.big.ac.cn/idog/images/breed_image_thumb/Xiasi_Dog.jpg']

for image_url in imagesList:
    filename = image_url.split("/")[-1]

    # Open the url image, set stream to True, this will return the stream content.
    r = requests.get(image_url, stream = True)

    # Check if the image was retrieved successfully
    if r.status_code == 200:
        # Set decode_content value to True, otherwise the downloaded image file's size will be zero.
        r.raw.decode_content = True
        
        # Open a local file with wb ( write binary ) permission.
        with open(f'pictures/{filename}','wb') as f:
            shutil.copyfileobj(r.raw, f)
            
        print('Image sucessfully Downloaded: ',filename)
    else:
        print('Image Couldn\'t be retreived')